#include <cstdint>
#include <windows.h>

namespace {

HMODULE SystemWinMm() {
    static HMODULE module = [] {
        wchar_t path[MAX_PATH] = {};
        const UINT length = GetSystemDirectoryW(path, MAX_PATH);
        constexpr UINT suffixLength = static_cast<UINT>(sizeof(L"\\winmm.dll") / sizeof(wchar_t));
        if (!length || length >= MAX_PATH - suffixLength)
            return static_cast<HMODULE>(nullptr);
        lstrcatW(path, L"\\winmm.dll");
        return LoadLibraryW(path);
    }();
    return module;
}

template <class T> T Resolve(const char *name) {
    HMODULE module = SystemWinMm();
    return module ? reinterpret_cast<T>(GetProcAddress(module, name)) : nullptr;
}

} // namespace

// URKit is x64-only. WinMM's public ABI uses integer and pointer arguments, so a
// single wide Win64 stub safely preserves every export without duplicating 180 signatures.
#define URK_WINMM_FORWARD(name)                                                                                        \
    extern "C" uintptr_t WINAPI Proxy_##name(uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5,    \
                                               uintptr_t a6, uintptr_t a7, uintptr_t a8, uintptr_t a9, uintptr_t a10,   \
                                               uintptr_t a11, uintptr_t a12) {                                          \
        using Fn = uintptr_t(WINAPI *)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t,    \
                                       uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t);                          \
        static Fn fn = Resolve<Fn>(#name);                                                                             \
        if (!fn) {                                                                                                     \
            SetLastError(ERROR_PROC_NOT_FOUND);                                                                        \
            return 0;                                                                                                  \
        }                                                                                                              \
        return fn(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);                                                  \
    }

URK_WINMM_FORWARD(mciExecute)
URK_WINMM_FORWARD(CloseDriver)
URK_WINMM_FORWARD(DefDriverProc)
URK_WINMM_FORWARD(DriverCallback)
URK_WINMM_FORWARD(DrvGetModuleHandle)
URK_WINMM_FORWARD(GetDriverModuleHandle)
URK_WINMM_FORWARD(OpenDriver)
URK_WINMM_FORWARD(PlaySound)
URK_WINMM_FORWARD(PlaySoundA)
URK_WINMM_FORWARD(PlaySoundW)
URK_WINMM_FORWARD(SendDriverMessage)
URK_WINMM_FORWARD(WOWAppExit)
URK_WINMM_FORWARD(auxGetDevCapsA)
URK_WINMM_FORWARD(auxGetDevCapsW)
URK_WINMM_FORWARD(auxGetNumDevs)
URK_WINMM_FORWARD(auxGetVolume)
URK_WINMM_FORWARD(auxOutMessage)
URK_WINMM_FORWARD(auxSetVolume)
URK_WINMM_FORWARD(joyConfigChanged)
URK_WINMM_FORWARD(joyGetDevCapsA)
URK_WINMM_FORWARD(joyGetDevCapsW)
URK_WINMM_FORWARD(joyGetNumDevs)
URK_WINMM_FORWARD(joyGetPos)
URK_WINMM_FORWARD(joyGetPosEx)
URK_WINMM_FORWARD(joyGetThreshold)
URK_WINMM_FORWARD(joyReleaseCapture)
URK_WINMM_FORWARD(joySetCapture)
URK_WINMM_FORWARD(joySetThreshold)
URK_WINMM_FORWARD(mciDriverNotify)
URK_WINMM_FORWARD(mciDriverYield)
URK_WINMM_FORWARD(mciFreeCommandResource)
URK_WINMM_FORWARD(mciGetCreatorTask)
URK_WINMM_FORWARD(mciGetDeviceIDA)
URK_WINMM_FORWARD(mciGetDeviceIDFromElementIDA)
URK_WINMM_FORWARD(mciGetDeviceIDFromElementIDW)
URK_WINMM_FORWARD(mciGetDeviceIDW)
URK_WINMM_FORWARD(mciGetDriverData)
URK_WINMM_FORWARD(mciGetErrorStringA)
URK_WINMM_FORWARD(mciGetErrorStringW)
URK_WINMM_FORWARD(mciGetYieldProc)
URK_WINMM_FORWARD(mciLoadCommandResource)
URK_WINMM_FORWARD(mciSendCommandA)
URK_WINMM_FORWARD(mciSendCommandW)
URK_WINMM_FORWARD(mciSendStringA)
URK_WINMM_FORWARD(mciSendStringW)
URK_WINMM_FORWARD(mciSetDriverData)
URK_WINMM_FORWARD(mciSetYieldProc)
URK_WINMM_FORWARD(midiConnect)
URK_WINMM_FORWARD(midiDisconnect)
URK_WINMM_FORWARD(midiInAddBuffer)
URK_WINMM_FORWARD(midiInClose)
URK_WINMM_FORWARD(midiInGetDevCapsA)
URK_WINMM_FORWARD(midiInGetDevCapsW)
URK_WINMM_FORWARD(midiInGetErrorTextA)
URK_WINMM_FORWARD(midiInGetErrorTextW)
URK_WINMM_FORWARD(midiInGetID)
URK_WINMM_FORWARD(midiInGetNumDevs)
URK_WINMM_FORWARD(midiInMessage)
URK_WINMM_FORWARD(midiInOpen)
URK_WINMM_FORWARD(midiInPrepareHeader)
URK_WINMM_FORWARD(midiInReset)
URK_WINMM_FORWARD(midiInStart)
URK_WINMM_FORWARD(midiInStop)
URK_WINMM_FORWARD(midiInUnprepareHeader)
URK_WINMM_FORWARD(midiOutCacheDrumPatches)
URK_WINMM_FORWARD(midiOutCachePatches)
URK_WINMM_FORWARD(midiOutClose)
URK_WINMM_FORWARD(midiOutGetDevCapsA)
URK_WINMM_FORWARD(midiOutGetDevCapsW)
URK_WINMM_FORWARD(midiOutGetErrorTextA)
URK_WINMM_FORWARD(midiOutGetErrorTextW)
URK_WINMM_FORWARD(midiOutGetID)
URK_WINMM_FORWARD(midiOutGetNumDevs)
URK_WINMM_FORWARD(midiOutGetVolume)
URK_WINMM_FORWARD(midiOutLongMsg)
URK_WINMM_FORWARD(midiOutMessage)
URK_WINMM_FORWARD(midiOutOpen)
URK_WINMM_FORWARD(midiOutPrepareHeader)
URK_WINMM_FORWARD(midiOutReset)
URK_WINMM_FORWARD(midiOutSetVolume)
URK_WINMM_FORWARD(midiOutShortMsg)
URK_WINMM_FORWARD(midiOutUnprepareHeader)
URK_WINMM_FORWARD(midiStreamClose)
URK_WINMM_FORWARD(midiStreamOpen)
URK_WINMM_FORWARD(midiStreamOut)
URK_WINMM_FORWARD(midiStreamPause)
URK_WINMM_FORWARD(midiStreamPosition)
URK_WINMM_FORWARD(midiStreamProperty)
URK_WINMM_FORWARD(midiStreamRestart)
URK_WINMM_FORWARD(midiStreamStop)
URK_WINMM_FORWARD(mixerClose)
URK_WINMM_FORWARD(mixerGetControlDetailsA)
URK_WINMM_FORWARD(mixerGetControlDetailsW)
URK_WINMM_FORWARD(mixerGetDevCapsA)
URK_WINMM_FORWARD(mixerGetDevCapsW)
URK_WINMM_FORWARD(mixerGetID)
URK_WINMM_FORWARD(mixerGetLineControlsA)
URK_WINMM_FORWARD(mixerGetLineControlsW)
URK_WINMM_FORWARD(mixerGetLineInfoA)
URK_WINMM_FORWARD(mixerGetLineInfoW)
URK_WINMM_FORWARD(mixerGetNumDevs)
URK_WINMM_FORWARD(mixerMessage)
URK_WINMM_FORWARD(mixerOpen)
URK_WINMM_FORWARD(mixerSetControlDetails)
URK_WINMM_FORWARD(mmDrvInstall)
URK_WINMM_FORWARD(mmGetCurrentTask)
URK_WINMM_FORWARD(mmTaskBlock)
URK_WINMM_FORWARD(mmTaskCreate)
URK_WINMM_FORWARD(mmTaskSignal)
URK_WINMM_FORWARD(mmTaskYield)
URK_WINMM_FORWARD(mmioAdvance)
URK_WINMM_FORWARD(mmioAscend)
URK_WINMM_FORWARD(mmioClose)
URK_WINMM_FORWARD(mmioCreateChunk)
URK_WINMM_FORWARD(mmioDescend)
URK_WINMM_FORWARD(mmioFlush)
URK_WINMM_FORWARD(mmioGetInfo)
URK_WINMM_FORWARD(mmioInstallIOProcA)
URK_WINMM_FORWARD(mmioInstallIOProcW)
URK_WINMM_FORWARD(mmioOpenA)
URK_WINMM_FORWARD(mmioOpenW)
URK_WINMM_FORWARD(mmioRead)
URK_WINMM_FORWARD(mmioRenameA)
URK_WINMM_FORWARD(mmioRenameW)
URK_WINMM_FORWARD(mmioSeek)
URK_WINMM_FORWARD(mmioSendMessage)
URK_WINMM_FORWARD(mmioSetBuffer)
URK_WINMM_FORWARD(mmioSetInfo)
URK_WINMM_FORWARD(mmioStringToFOURCCA)
URK_WINMM_FORWARD(mmioStringToFOURCCW)
URK_WINMM_FORWARD(mmioWrite)
URK_WINMM_FORWARD(mmsystemGetVersion)
URK_WINMM_FORWARD(sndPlaySoundA)
URK_WINMM_FORWARD(sndPlaySoundW)
URK_WINMM_FORWARD(timeBeginPeriod)
URK_WINMM_FORWARD(timeEndPeriod)
URK_WINMM_FORWARD(timeGetDevCaps)
URK_WINMM_FORWARD(timeGetSystemTime)
URK_WINMM_FORWARD(timeGetTime)
URK_WINMM_FORWARD(timeKillEvent)
URK_WINMM_FORWARD(timeSetEvent)
URK_WINMM_FORWARD(waveInAddBuffer)
URK_WINMM_FORWARD(waveInClose)
URK_WINMM_FORWARD(waveInGetDevCapsA)
URK_WINMM_FORWARD(waveInGetDevCapsW)
URK_WINMM_FORWARD(waveInGetErrorTextA)
URK_WINMM_FORWARD(waveInGetErrorTextW)
URK_WINMM_FORWARD(waveInGetID)
URK_WINMM_FORWARD(waveInGetNumDevs)
URK_WINMM_FORWARD(waveInGetPosition)
URK_WINMM_FORWARD(waveInMessage)
URK_WINMM_FORWARD(waveInOpen)
URK_WINMM_FORWARD(waveInPrepareHeader)
URK_WINMM_FORWARD(waveInReset)
URK_WINMM_FORWARD(waveInStart)
URK_WINMM_FORWARD(waveInStop)
URK_WINMM_FORWARD(waveInUnprepareHeader)
URK_WINMM_FORWARD(waveOutBreakLoop)
URK_WINMM_FORWARD(waveOutClose)
URK_WINMM_FORWARD(waveOutGetDevCapsA)
URK_WINMM_FORWARD(waveOutGetDevCapsW)
URK_WINMM_FORWARD(waveOutGetErrorTextA)
URK_WINMM_FORWARD(waveOutGetErrorTextW)
URK_WINMM_FORWARD(waveOutGetID)
URK_WINMM_FORWARD(waveOutGetNumDevs)
URK_WINMM_FORWARD(waveOutGetPitch)
URK_WINMM_FORWARD(waveOutGetPlaybackRate)
URK_WINMM_FORWARD(waveOutGetPosition)
URK_WINMM_FORWARD(waveOutGetVolume)
URK_WINMM_FORWARD(waveOutMessage)
URK_WINMM_FORWARD(waveOutOpen)
URK_WINMM_FORWARD(waveOutPause)
URK_WINMM_FORWARD(waveOutPrepareHeader)
URK_WINMM_FORWARD(waveOutReset)
URK_WINMM_FORWARD(waveOutRestart)
URK_WINMM_FORWARD(waveOutSetPitch)
URK_WINMM_FORWARD(waveOutSetPlaybackRate)
URK_WINMM_FORWARD(waveOutSetVolume)
URK_WINMM_FORWARD(waveOutUnprepareHeader)
URK_WINMM_FORWARD(waveOutWrite)

#undef URK_WINMM_FORWARD
